# @file      west.yml
# @author    Theodore Bardy
#
# @note      This file is part of Witekio's Zephyr Demo project
# @brief     West manifest file including Zephyr module

manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2.0
      import: true

    - name: mender-mcu
      url: https://github.com/mendersoftware/mender-mcu
      revision: 87b880a5f7987ae169a681dc8ef1b266089871ef
      path: modules/mender-mcu
      import: true